config/routes.rb
AuctionApp::Application.routes.draw do

  resources :users

  get '/auctions' => 'auctions#index'
  get '/auctions/new' => 'auctions#new'
  post '/auctions' => 'auctions#create'
  get '/auctions/:id' => 'auctions#show', :as => :auction
  
  get '/auctions/:id/bids/new' => 'bids#new', :as => :new_auction_bid
  post '/auctions/:id/bids' => 'bids#create', :as => :auction_bids

  

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  belongs_to :seller, :class_name => "User"
  has_many :bids
  
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :bidder, :class_name => "User"
  belongs_to :auction
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :listings, :class_name => "Auction", :foreign_key => "seller_id"

  has_many :bids, :foreign_key => "bidder_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  def index
    @auctions = Auction.all
  end
  
  def new
    @auction = Auction.new
  end

  def create
    @a = Auction.new(auction_params)
    @a.save

    redirect_to(@a)
  end

  def show
    @auction = Auction.find(params[:id])
  end

  private
    def auction_params
      params.require(:auction).permit(:name, :seller_id)
    end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  def new
    @auction = Auction.find(params[:id])
    @bid = Bid.new
  end

  def create
    @auction = Auction.find(params[:id])
    @bid = @auction.bids.build(bid_params)
    @bid.save

    redirect_to @auction
  end

  private
    def bid_params
      params.require(:bid).permit(:amount, :bidder_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/index.html.erb
Auctions:

<ul>
<% @auctions.each do |auction| %>
  <li><%= link_to auction.name, auction %></li>
<% end %>

app/views/auctions/new.html.erb
<h1>Create a New Auction</h1>

<%#= form_for(@auction, :url => '/auctions') do |f| %>
<%= form_for(@auction) do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <% seller_options = User.all.collect{|u| [u.name, u.id]}%>
    <%= f.select(:seller_id, seller_options) %>
  </p>



  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/auctions/show.html.erb
<p>Name: <%= @auction.name %></p>
<p>Seller: <%= @auction.seller.name %></p>

<p>Current Bids</p>

<ol>
<% @auction.bids.each do |bid| %>
  <li><%= bid.amount %> - <%= bid.bidder.name %></li>
<% end %>
</ol>

<%= link_to "Bid on This Item", new_auction_bid_path(@auction) %>

app/views/bids/new.html.erb
<%#= form_for(@auction, :url => '/auctions') do |f| %>
You are bidding on: <%= @auction.name %>

<%= form_for(@bid, :url => auction_bids_path(@auction)) do |f| %>
  <%#= f.hidden_field :auction_id, @auction.id %>
  <p>
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </p>

  <p>
    <% bidder_options = User.all.collect{|u| [u.name, u.id]}%>
    <%= f.select(:bidder_id, bidder_options) %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuctionApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>